version: '3'

services:
  postgresql:
    image: postgres:16-alpine
    restart: always
    ports:
      - 45432:5432
    volumes:
      - ./docker/postgresql/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: admin
      TZ: 'Asia/Tokyo'
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 84:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgresql
