version: '3'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command:
      [
        'bash',
        '-c',
        'echo ''alias ll="ls -l"'' >> ~/.bashrc && pip install -r environ/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 1',
      ]
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 45432:5432
    volumes:
      - ./docker/postgresql/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: admin
      TZ: 'Asia/Tokyo'
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 84:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres

  nginx:
    image: nginx
    ports:
      - 8001:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/images:/home/images
    depends_on:
      - app
