@startuml tables

entity alerts as "alerts\nアラート" {
  + alert_id [PK]
  --
  picture_id
  status [ステータス]
  created_at [作成日]
  updated_at [更新日]
}

entity pictures as "pictures\nピクチャ" {
  + picture_id [PK]
  --
  alert_id
  picture [画像]
  created_at [作成日]
  updated_at [更新日]
}


@enduml
